name: smartscanner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build smartscanner
        run: go build -o smartscanner ./cmd/nuclei
      - name: Run scan (SARIF)
        run: ./smartscanner scan . --format sarif --sarif-out smartscanner.sarif || true
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: smartscanner.sarif

